language: php

php:
#  - 5.3
#  - 5.3.3
  - 5.4
#  - 5.5

env:
  - SYMFONY_VERSION=v2.2.1
#  - SYMFONY_VERSION=v2.2.0
#  - SYMFONY_VERSION=v2.0.23

before_script:
  - sh -c 'if [ $(php -r "echo PHP_MINOR_VERSION;") -le 4 ]; then echo "extension = apc.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi;'
  - composer self-update
  - composer install --dev
  - composer dump-autoload
