language: php

php:
#  - 5.3
#  - 5.3.3
  - 5.4
#  - 5.5

env:
  - SYMFONY_VERSION=v2.2.1
#  - SYMFONY_VERSION=v2.2.0
#  - SYMFONY_VERSION=v2.0.23

before_script:
  - composer self-update
  - composer install --dev
  - composer require mpskeeter/nbbc:dev-travis
  - composer update
