_welcome:
    pattern:  /
    defaults: { _controller: PoaMainBundle:Welcome:index }

_about_us:
    pattern: /about
    defaults: {_controller: PoaMainBundle:Content:index }

_amenities:
    pattern: /amenities
    defaults: {_controller: PoaMainBundle:Content:index }

_board:
    pattern: /board
    defaults: {_controller: PoaMainBundle:Content:index }

_management:
    pattern: /management
    defaults: {_controller: PoaMainBundle:Content:index }

_committees:
    pattern: /committees
    defaults: {_controller: PoaMainBundle:Content:index }

_pool:
    pattern: /pool
    defaults: {_controller: PoaMainBundle:Content:index }

_documents:
    pattern: /documents
    defaults: {_controller: PoaMainBundle:Content:index }

_faq:
    pattern: /faq
    defaults: {_controller: PoaMainBundle:Faq:index }

_community:
    pattern: /community
    defaults: {_controller: PoaMainBundle:Content:index }

_utility:
    pattern: /utility
    defaults: {_controller: PoaMainBundle:Content:index }

_facebook:
    pattern: /facebook
    defaults: {_controller: PoaMainBundle:Content:index }

_directory:
    pattern: /directory
    defaults: {_controller: PoaMainBundle:Content:index }

_board:
    pattern: /board
    defaults: {_controller: PoaMainBundle:Content:index }

_download:
    pattern:  /download/{filename}
    defaults: {_controller: PoaMainBundle:Content:download }

_user_bundle:
    resource: "@UserBundle/Resources/config/routing.yml"

admin:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin

sonata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /media/gallery

media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media

sonata_page_cache:
    resource: '@SonataCacheBundle/Resources/config/routing/cache.xml'
    prefix: /
