jms_security_extra:
    secure_all_services: false
    expressions: true

security:
#    encoders:
#        Symfony\Component\Security\Core\User\User: plaintext
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
#        chain_providers:
#            chain:
#                providers: [fos_userbundle, fos_facebook_providers]
        fos_userbundle:
            id: fos_user.user_provider.username
#        fos_facebook_providers:
#            id: fos_facebook_user

    firewalls:
        main:
            pattern:    ^/
#            fos_facebook:
#                app_url: "http://apps.facebook.com/BallardWoods_Test/"
#                server_url: "http://test.skeeter-net.net/"
#                login_path: fos_user_security_login
#                check_path: fos_facebook_security_check
#                default_target_path: /
            form_login:
                provider: fos_userbundle
#                check_path: _security_check
                login_path: _demo_login
                csrf_provider: form.csrf_provider
            logout: true
            anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }

