services:
    twig.extension.poa.main:
        class: Poa\MainBundle\Twig\Extension\MainExtension
        public: false
        arguments: [%twig.loader%]
        tags:
            - { name: twig.extension }

    poa.main.listener:
        class: Poa\MainBundle\EventListener\ControllerListener
        arguments: [%twig.extension.poa.main%]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }

    poa_user.registration.form.type:
        class: Poa\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: poa_user_registration }

    fos_user.facebook_provider.user:
        class: Poa\UserBundle\Security\User\Provider\FacebookProvider
        arguments:
            facebook: "@fos_facebook.api"
            userManager: "@fos_user.user_manager"
            validator: "@validator"
            container: "@service_container"

