services:
    twig.extension.poa.main:
        class: Poa\MainBundle\Twig\Extension\MainExtension
        public: false
        arguments: [%twig.loader%]
        tags:
            - { name: twig.extension }

    poa.main.listener:
        class: Poa\MainBundle\EventListener\ControllerListener
        arguments: [%twig.extension.poa.main%]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }

   poa_user.registration.form.type:
        class: Poa\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: poa_user_registration }

