<?php

	namespace Poa\MainBundle\Entity;

	use Doctrine\ORM\EntityRepository;

	/**
	 * ContentRepository
	 *
	 * This class was generated by the Doctrine ORM. Add your own custom
	 * repository methods below.
	 */
	class ContentRepository extends EntityRepository
	{
		public function getMenuID($id) {
			$pages = $this->createQueryBuilder('m')
				->andWhere('m.menu_order = ?1')
				->andWhere('m.menu_active = ?2')
				->andWhere('m.menu_depth = 0')
				->addOrderBy('m.menu_order')
				->setParameter(1, $id)
				->setParameter(2, true)
				->getQuery()->getResult();
			return $pages;
		}

		public function getNonExpiredMenuForParent($parent_id) {
			$pages = $this->createQueryBuilder('c')
				->andWhere('c.active = ?1')
				->andWhere('c.menu_item = ?2')
				->andWhere('(c.expires IS NULL OR c.expires >= CURRENT_TIMESTAMP())')
				->addOrderBy('c.sequence')
				->setParameter(1, true)
				->setParameter(2, $parent_id)
				->getQuery()->getResult();
			return $pages;
		}

		public function getAllMenuForParent($parent_id) {
			$pages = $this->createQueryBuilder('c')
				->andWhere('c.active = ?1')
				->andWhere('c.menu_item = ?2')
				->addOrderBy('c.sequence')
				->setParameter(1, true)
				->setParameter(2, $parent_id)
				->getQuery()->getResult();
			return $pages;
		}

		public function getMenusByDepth($depth) {
			$pages = $this->createQueryBuilder('n')
				->andWhere('n.menu_active = ?1')
				->andWhere('n.menu_depth = ?2')
				->addOrderBy('n.menu_order')
				->setParameter(1, true)
				->setParameter(2, $depth)
				->getQuery()->getResult();
			return $pages;
		}
	}