<?php

	namespace Poa\MainBundle\Entity;

	use Doctrine\ORM\EntityRepository;

	/**
	 * FaqRepository
	 *
	 * This class was generated by the Doctrine ORM. Add your own custom
	 * repository methods below.
	 */
	class FaqRepository extends EntityRepository
	{
		public function findActive() {
			$faqs = $this->createQueryBuilder('f')
				->andWhere('f.active = ?1')
				->addOrderBy('f.sequence')
				->setParameter(1, true)
				->getQuery()->getResult();
			return $faqs;
		}
	}