<?php

namespace Poa\ForumBundle\DependencyInjection;

use Symfony\Component\Config\Definition\ConfigurationInterface;
use Symfony\Component\Config\Definition\Builder\TreeBuilder;

/**
 * Forum configuration
 *
 * @author Antoine Hérault <antoine.herault@gmail.com>
 */
class Configuration implements ConfigurationInterface
{
    /**
     * {@inheritDoc}
     */
    public function getConfigTreeBuilder()
    {
        $treeBuilder = new TreeBuilder();
        $rootNode = $treeBuilder->root('poa_forum');

        $rootNode
            ->children()
                ->scalarNode('db_driver')
                    ->isRequired()
                    ->validate()
                        ->ifNotInArray(array('orm', 'odm'))
                        ->thenInvalid('The database driver must be either \'orm\' or \'odm\'.')
                    ->end()
                ->end()
                ->arrayNode('class')
                    ->isRequired()
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->arrayNode('model')
                            ->isRequired()
                            ->children()
                                ->scalarNode('category')->isRequired()->end()
                                ->scalarNode('topic')->isRequired()->end()
                                ->scalarNode('post')->isRequired()->end()
                            ->end()
                        ->end()
                        ->arrayNode('form')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->scalarNode('new_topic')->defaultValue('Poa\ForumBundle\Form\NewTopicFormType')->end()
                                ->scalarNode('first_post')->defaultValue('Poa\ForumBundle\Form\PostFormType')->end()
                                ->scalarNode('post')->defaultValue('Poa\ForumBundle\Form\PostFormType')->end()
                                ->scalarNode('search')->defaultValue('Poa\ForumBundle\Form\SearchFormType')->end()
								->scalarNode('edit_post')->defaultValue('Poa\ForumBundle\Form\PostFormType')->end()
                            ->end()
                        ->end()
                        ->arrayNode('controller')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->scalarNode('forum')->defaultValue('Poa\ForumBundle\Controller\ForumController')->end()
                                ->scalarNode('category')->defaultValue('Poa\ForumBundle\Controller\CategoryController')->end()
                                ->scalarNode('topic')->defaultValue('Poa\ForumBundle\Controller\TopicController')->end()
                                ->scalarNode('post')->defaultValue('Poa\ForumBundle\Controller\PostController')->end()
                            ->end()
                        ->end()
                        ->arrayNode('creator')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->scalarNode('topic')->defaultValue('Poa\ForumBundle\Creator\TopicCreator')->end()
                                ->scalarNode('post')->defaultValue('Poa\ForumBundle\Creator\PostCreator')->end()
                            ->end()
                        ->end()
                        ->arrayNode('blamer')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->scalarNode('topic')->defaultValue('Poa\ForumBundle\Blamer\TopicBlamer')->end()
                                ->scalarNode('post')->defaultValue('Poa\ForumBundle\Blamer\PostBlamer')->end()
                            ->end()
                        ->end()
                        ->arrayNode('updater')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->scalarNode('category')->defaultValue('Poa\ForumBundle\Updater\CategoryUpdater')->end()
                                ->scalarNode('topic')->defaultValue('Poa\ForumBundle\Updater\TopicUpdater')->end()
								->scalarNode('post')->defaultValue('Poa\ForumBundle\Updater\PostUpdater')->end()
                            ->end()
                        ->end()
                        ->arrayNode('remover')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->scalarNode('topic')->defaultValue('Poa\ForumBundle\Remover\TopicRemover')->end()
                                ->scalarNode('post')->defaultValue('Poa\ForumBundle\Remover\PostRemover')->end()
                            ->end()
                        ->end()
                        ->arrayNode('twig')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->scalarNode('extension')->defaultValue('Poa\ForumBundle\Twig\ForumExtension')->end()
                            ->end()
                        ->end()
                        ->arrayNode('router')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->scalarNode('url_generator')->defaultValue('Poa\ForumBundle\Router\ForumUrlGenerator')->end()
                            ->end()
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('form_name')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->scalarNode('new_topic')->defaultValue('forum_new_topic_form')->end()
                        ->scalarNode('first_post')->defaultValue('firstPost')->end()
                        ->scalarNode('post')->defaultValue('forum_post_form')->end()
                        ->scalarNode('search')->defaultValue('forum_search')->end()
						->scalarNode('edit_post')->defaultValue('forum_edit_post')->end()
                    ->end()
                ->end()
                ->arrayNode('paginator')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->scalarNode('posts_per_page')->defaultValue(10)->end()
                        ->scalarNode('topics_per_page')->defaultValue(10)->end()
                        ->scalarNode('search_results_per_page')->defaultValue(10)->end()
                    ->end()
                ->end()
                ->arrayNode('templating')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->arrayNode('location')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->scalarNode('category')->defaultValue('PoaForumBundle:Category')->end()
                                ->scalarNode('forum')->defaultValue('PoaForumBundle:Forum')->end()
                                ->scalarNode('post')->defaultValue('PoaForumBundle:Post')->end()
                                ->scalarNode('topic')->defaultValue('PoaForumBundle:Topic')->end()
                            ->end()
                        ->end()                    
                        ->scalarNode('engine')
                            ->defaultValue('twig')
                            ->validate()
                                ->ifNotInArray(array('twig', 'php'))
                                ->thenInvalid('The templating engine must be either \'twig\' or \'php\'.')
                            ->end()
                        ->end()
                        ->scalarNode('theme')->defaultValue('Twig::form.html.twig')->end()
                    ->end()
                ->end()
            ->end()
        ;

        return $treeBuilder;
    }
}
