<?php

	namespace Poa\UserBundle\Entity;

	use Doctrine\ORM\EntityRepository;

	/**
	 * PetsRepository
	 *
	 * This class was generated by the Doctrine ORM. Add your own custom
	 * repository methods below.
	 */
	class PetsRepository extends EntityRepository
	{
		public function getAllPetsForOwner($owner_id) {
			$pages = $this->createQueryBuilder('p')
				->andWhere('p.active = ?1')
				->andWhere('p.owner = ?2')
				->setParameter(1, true)
				->setParameter(2, $owner_id)
				->getQuery()->getResult();
			return $pages;
		}
	}