parameters:
    my_user_provider.class: Poa\UserBundle\Security\User\Provider\FOSUBUserProvider

services:
    poa_user.registration.form.type:
        class: Poa\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: poa_user_registration }

    my_user_provider:
        class: "%my_user_provider.class%"
        #this is the place where the properties are passed to the UserProvider - see config.yml
#        arguments: [@fos_user.user_manager,{facebook: facebook_id, google: google_id}]
        arguments: [@fos_user.user_manager,{facebook: facebook_uid, google: google_uid}]

#    poa_user.profile.form.type:
#        class: Poa\UserBundle\Form\Type\ProfileType
#        arguments: [%fos_user.model.user.class%]
#        tags:
#            - { name: form.type, alias: poa_user_profile }

#        <service id="sonata.user.profile.form.type" class="Poa\UserBundle\Form\ProfileType">
#            <argument>%fos_user.model.user.class%</argument>
#            <tag name="form.type" alias="poa_user_profile" />
#        </service>


