# src/Poa/BlogBundle/Resources/config/routing.yml

_forum:
    pattern:  /forum
    defaults: { _controller: PoaBlogBundle:Blog:showAll }

PoaBlogBundle_blog_show:
    pattern:  /forum/{id}
    defaults: { _controller: PoaBlogBundle:Blog:show }
    requirements:
        _method:  GET
        id: \d+